2022-03-21 04:32:24 info: ---------------------------------------
2022-03-21 04:32:24 info: >>> Running Unit Test `ex1-johnWho` <<<
2022-03-21 04:32:24 info: ---------------------------------------
2022-03-21 04:32:31 error: *** Unit Test Error Report ***

Command failed: npx jest ex1-johnWho.test.js --colors
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Error: You didn't pass in a first name!".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
2022-03-21 04:32:34 error: *** ESLint Report ***

ex1-johnWho.js
   3:9   error  'reject' is assigned a value but never used   no-unused-vars
  15:33  error  'callback' is defined but never used          no-unused-vars
  16:9   error  'promise' is assigned a value but never used  no-unused-vars

✖ 3 problems (3 errors, 0 warnings)


2022-03-21 04:39:33 info: ---------------------------------------
2022-03-21 04:39:33 info: >>> Running Unit Test `ex1-johnWho` <<<
2022-03-21 04:39:33 info: ---------------------------------------
2022-03-21 04:39:37 error: *** Unit Test Error Report ***

Command failed: npx jest ex1-johnWho.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js
  getAnonName
    ✓ should exist and be executable (2 ms)
    ✕ should have all TODO comments removed (2 ms)
    ✓ `getAnonName` should not contain unneeded console.log calls (1 ms)
    ✓ should call `new Promise()`
    ✓ should take a single argument
    ✓ `resolve()` should be called with a one argument
    ✓ `reject()` should be called with a one argument (1 ms)
    ✓ should resolve when called with a string argument (2 ms)
    ✓ should reject with an Error object when called without an argument (2 ms)

  ● getAnonName › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.<anonymous> (test-runner/unit-test-helpers.js:105:42)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 8 passed, 9 total
Snapshots:   0 total
Time:        0.995 s
Ran all test suites matching /ex1-johnWho.test.js/i.
2022-03-21 04:39:40 error: *** ESLint Report ***

ex1-johnWho.js
  3:9  error  'reject' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)


2022-03-21 04:40:40 info: ---------------------------------------
2022-03-21 04:40:40 info: >>> Running Unit Test `ex1-johnWho` <<<
2022-03-21 04:40:40 info: ---------------------------------------
2022-03-21 04:40:45 info: All unit tests passed.
2022-03-21 04:40:48 error: *** ESLint Report ***

ex1-johnWho.js
  3:9  error  'reject' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)


2022-03-21 04:43:53 info: ---------------------------------------
2022-03-21 04:43:53 info: >>> Running Unit Test `ex1-johnWho` <<<
2022-03-21 04:43:53 info: ---------------------------------------
2022-03-21 04:43:58 info: All unit tests passed.
2022-03-21 04:44:00 error: *** ESLint Report ***

ex1-johnWho.js
  3:9  error  'reject' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)


2022-03-21 04:45:27 info: ---------------------------------------
2022-03-21 04:45:27 info: >>> Running Unit Test `ex1-johnWho` <<<
2022-03-21 04:45:27 info: ---------------------------------------
2022-03-21 04:45:31 info: All unit tests passed.
2022-03-21 04:45:33 error: *** ESLint Report ***

ex1-johnWho.js
  3:9  error  'reject' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)


2022-03-21 04:47:43 info: ---------------------------------------
2022-03-21 04:47:43 info: >>> Running Unit Test `ex1-johnWho` <<<
2022-03-21 04:47:43 info: ---------------------------------------
2022-03-21 04:47:49 info: All unit tests passed.
2022-03-21 04:47:54 info: All steps were completed successfully
2022-03-21 05:22:43 info: -------------------------------------------------
2022-03-21 05:22:43 info: >>> Running Unit Test `ex2-checkDoubleDigits` <<<
2022-03-21 05:22:43 info: -------------------------------------------------
2022-03-21 05:22:52 info: All unit tests passed.
2022-03-21 05:22:54 error: *** ESLint Report ***

ex2-checkDoubleDigits.js
  3:9  error  'reject' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)


2022-03-21 05:24:14 info: -------------------------------------------------
2022-03-21 05:24:14 info: >>> Running Unit Test `ex2-checkDoubleDigits` <<<
2022-03-21 05:24:14 info: -------------------------------------------------
2022-03-21 05:24:22 info: All unit tests passed.
2022-03-21 05:24:26 info: All steps were completed successfully
2022-03-21 06:34:40 info: -----------------------------------------
2022-03-21 06:34:40 info: >>> Running Unit Test `ex3-rollAnAce` <<<
2022-03-21 06:34:40 info: -----------------------------------------
2022-03-21 06:34:40 info: Exercise has not yet been modified
2022-03-21 06:34:46 error: *** Unit Test Error Report ***

Command failed: npx jest ex3-rollAnAce.test.js --colors
 FAIL  3-UsingAPIs/Week2/unit-tests/ex3-rollAnAce.test.js
  ex3-rollAnAce
    ✕ should have all TODO comments removed (3 ms)
    ✓ `rollDieUntil` should not contain unneeded console.log calls
    ✕ should not include a recursive call (1 ms)
    ✕ should use async/wait (1 ms)
    ✕ should use try/catch
    ✓ should resolve as soon as a die settles on an ACE (33 ms)
    ✓ should reject with an Error when a die rolls off the table (12 ms)

  ● ex3-rollAnAce › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.<anonymous> (test-runner/unit-test-helpers.js:105:42)

  ● ex3-rollAnAce › should not include a recursive call

    expect(received).toBeUndefined()

    Received: true

      53 |
      54 |   test('should not include a recursive call', () => {
    > 55 |     expect(state.recursive).toBeUndefined();
         |                             ^
      56 |   });
      57 |
      58 |   test('should use async/wait', () => {

      at Object.<anonymous> (3-UsingAPIs/Week2/unit-tests/ex3-rollAnAce.test.js:55:29)

  ● ex3-rollAnAce › should use async/wait

    expect(received).toBeDefined()

    Received: undefined

      57 |
      58 |   test('should use async/wait', () => {
    > 59 |     expect(state.async).toBeDefined();
         |                         ^
      60 |     expect(state.await).toBeDefined();
      61 |   });
      62 |

      at Object.<anonymous> (3-UsingAPIs/Week2/unit-tests/ex3-rollAnAce.test.js:59:25)

  ● ex3-rollAnAce › should use try/catch

    expect(received).toBeDefined()

    Received: undefined

      62 |
      63 |   test('should use try/catch', () => {
    > 64 |     expect(state.tryCatch).toBeDefined();
         |                            ^
      65 |   });
      66 |
      67 |   test('should resolve as soon as a die settles on an ACE', async () => {

      at Object.<anonymous> (3-UsingAPIs/Week2/unit-tests/ex3-rollAnAce.test.js:64:28)

Test Suites: 1 failed, 1 total
Tests:       4 failed, 3 passed, 7 total
Snapshots:   0 total
Time:        1.201 s
Ran all test suites matching /ex3-rollAnAce.test.js/i.
2022-03-21 06:35:07 info: ---------------------------------------
2022-03-21 06:35:07 info: >>> Running Unit Test `ex3-rollDie` <<<
2022-03-21 06:35:07 info: ---------------------------------------
2022-03-21 06:35:11 info: All unit tests passed.
2022-03-21 06:35:15 info: All steps were completed successfully
2022-03-21 01:41:24 info: --------------------------------------------
2022-03-21 01:41:24 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2022-03-21 01:41:24 info: --------------------------------------------
2022-03-21 01:41:28 error: *** Unit Test Error Report ***

Command failed: npx jest ex4-pokerDiceAll.test.js --colors
 FAIL  3-UsingAPIs/Week1/unit-tests/ex4-pokerDiceAll.test.js
  ex4-pokerDiceAll
    ✓ should exist and be executable (1 ms)
    ✕ should have all TODO comments removed (2 ms)
    ✓ `rollDice` should not contain unneeded console.log calls
    ✓ should use `dice.map()`
    ✓ should use `Promise.all()`
    ✓ should resolve when all dice settle successfully (2 ms)
    ✕ should reject with an Error when a die rolls off the table (3 ms)

  ● ex4-pokerDiceAll › should have all TODO comments removed

    expect(received).toBeFalsy()

    Received: true

      103 | function testTodosRemoved(getSource) {
      104 |   test('should have all TODO comments removed', () => {
    > 105 |     expect(/\bTODO\b/.test(getSource())).toBeFalsy();
          |                                          ^
      106 |   });
      107 | }
      108 |

      at Object.<anonymous> (test-runner/unit-test-helpers.js:105:42)

  ● ex4-pokerDiceAll › should reject with an Error when a die rolls off the table

    expect.assertions(3)

    Expected three assertions to be called but received two assertion calls.

      63 |
      64 |   test('should reject with an Error when a die rolls off the table', async () => {
    > 65 |     expect.assertions(3);
         |            ^
      66 |     expect(exported).toBeDefined();
      67 |
      68 |     const randomSpy = jest.spyOn(Math, 'random').mockReturnValue(0.999);

      at Object.<anonymous> (3-UsingAPIs/Week1/unit-tests/ex4-pokerDiceAll.test.js:65:12)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 5 passed, 7 total
Snapshots:   0 total
Time:        1.011 s
Ran all test suites matching /ex4-pokerDiceAll.test.js/i.
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Error: Die 1 rolled off the table.
".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
2022-03-21 01:43:33 info: --------------------------------------------
2022-03-21 01:43:33 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2022-03-21 01:43:33 info: --------------------------------------------
2022-03-21 01:43:39 info: All unit tests passed.
2022-03-21 01:43:44 info: All steps were completed successfully
2022-03-21 08:27:59 info: ----------------------------------------------
2022-03-21 08:27:59 info: >>> Running Unit Test `ex5-pokerDiceChain` <<<
2022-03-21 08:27:59 info: ----------------------------------------------
2022-03-21 08:28:03 info: All unit tests passed.
2022-03-21 08:28:09 info: All steps were completed successfully
